### ISSUE TITLE
Updates needed to complete adoption to typesense github org

### ISSUE THREAD

**Issue by jasonbosco** [typesense/laravel-scout-typesense-driver#1]
This repo was adopted from @AbdullahFaqeir's work here: https://github.com/devloopsnet/laravel-scout-typesense-engine.

The following tasks need to be done to complete the adoption:

- [x] Add LICENSE file (current license MIT)
- [x] Add credits to Abdullah Al-Faqeir and his company DevLoops for building the original version, in README
- [x] Change instances of `Devloops` in class names to `Typesense`
- [x] `TypesenseServiceProvider.php` has references to `master_node` and `read_replica_nodes`, which are old configuration parameters no longer supported in the latest version of Typesense Server. Needs to be switched to `nodes` and `nearest_node`
- [x] Publish new version of package under typesense namespace - @jasonbosco 
- [x] Test that new published version works fine
- [x] Mark `devloopsnet/laravel-typesense` [as abandoned](https://stackoverflow.com/questions/40946151/marking-a-packagist-package-as-abandoned-in-favor-of-a-new-location) in Packagist and list this package as its replacement
- [x] Update README.md in `devloopsnet/laravel-scout-typesense-engine` repo to point people to this repo: https://github.com/devloopsnet/laravel-scout-typesense-engine/issues/17

**Comment by hi019** [comment]
We should also mark devloopsnet/laravel-typesense as abandoned in Packagist and list this as its replacement, assuming that is the case

**Comment by jasonbosco** [comment]
Ah, didn't know that was a thing. Thanks @hi019. I've added it to the list.

**Comment by jasonbosco** [comment]
Also, do you want to take a stab at making these updates? :)

**Comment by hi019** [comment]
Yes, I was going to do that. I did a similar thing for https://github.com/hi019/laravel-scout-typesense :)

**Comment by hi019** [comment]
I'll also implement my changes from my fork here when I have time

**Comment by jasonbosco** [comment]
Awesome! Thank you. I'll assign this issue to you, so others know that you're working on it.

**Comment by jasonbosco** [comment]
@hi019 On a side note, I'd love to invite you to join our [Slack community](https://join.slack.com/t/typesense-community/shared_invite/zt-mx4nbsbn-AuOL89O7iBtvkz136egSJg) in case we need to chat in real-time.

**Comment by manavo** [comment]
Guess the issue description at the top needs updating now that the PR is merged? Not sure what’s left now, or is the migration complete?

**Comment by jasonbosco** [comment]
@hi019 Mind updating the checklist in this PR's description?

**Comment by hi019** [comment]
Yep, I'll update it later today. Forgot I had edit permissions :)

**Comment by hi019** [comment]
Everything is done on this repository's side 👍

**Comment by jasonbosco** [comment]
Thank you @hi019! 

I was going to publish the package to packagist, but I wanted to confirm if the package/repo naming convention is ok. Looking at a couple of other Laravel Scout packages, they're all named laravel-scout-x-driver. 

Eg:

- https://github.com/babenkoivan/scout-elasticsearch-driver
- https://github.com/yabhq/laravel-scout-mysql-driver

Should we also change this repo/package name to laravel-scout-typesense-driver? Is there a common convention?

Also, is a Laravel Scout "engine" different from a Scout "driver"?

**Comment by hi019** [comment]
From what I understand after reading the [Scout docs](https://laravel.com/docs/8.x/scout), an engine is the search provider itself, like Algolia or in this case Typesense. And a driver is what interfaces between the engine and Laravel code.

So, while I can't find any Scout naming conventions, it would make sense to name this repository & the package `laravel-scout-typesense-driver`.

**Comment by hi019** [comment]
@jasonbosco Can you wait until tomorrow to publish the package? I forgot to integrate the bulk delete API route I mentioned earlier in this Issue. It would likely be a small breaking change, so it would be easier to just put it in the migration notes before the package is available

**Comment by jasonbosco** [comment]
@hi019 Sounds good. I'll stand by.

And thank you for the research on naming the repo & package.

**Comment by hi019** [comment]
Unfortunately I won't have time to do this today, will complete it tomorrow

**Comment by hi019** [comment]
@jasonbosco Ready for release

**Comment by jasonbosco** [comment]
@hi019 Thank you. I've published an RC version of the package here: https://packagist.org/packages/typesense/laravel-scout-typesense-driver

Could you give it a shot and let me know if it works ok?

**Comment by manavo** [comment]
I'm getting errors on the soft delete checks:

```
ErrorException: Undefined property: Typesense\LaravelTypesense\Engines\TypesenseEngine::$softDelete
```

**Comment by manavo** [comment]
I've made PR #5 to fix it

**Comment by manavo** [comment]
The issue is solved if I specifically define the `getScoutKeyName()` method:

```php
    public function getScoutKeyName() {
        return 'id';
    }
```

But it would be good if this worked without needing to explicitly define that!

**Comment by hi019** [comment]
Interesting, will look into it later today @manavo . Do your models use the `Searchable` trait? That defines getScoutKeyName

```
    /**
     * @return mixed
     */
    public function getScoutKeyName()
    {
        return 'uuid';
    }
```

**Comment by hi019** [comment]
I'll look into it later today @manavo . Do your models use the trait `Laravel\Scout\Searchable`? It defines a `getScoutKeyName` method.

**Comment by manavo** [comment]
Yep, it uses the trait, but the one in the trait does this:

```php
    public function getScoutKeyName()
    {
        return $this->getQualifiedKeyName();
    }
```

And it makes me think that it is meant to be used in the Eloquent Query Builder, more than in the engines/drivers.

Even when I forced it to be just `id` instead of `{TABLE_NAME}.id`, I still get this error:

```
Could not find a filter field named `id` in the schema
```

So I'm not sure why that is. I'm guessing Typesense should let us filter by `id`?

**Comment by manavo** [comment]
I'm also running version `0.17.0` of Typesense, so I'll try and upgrade and see what happens.

**Comment by hi019** [comment]
@manavo Do you mind creating a new issue for this so it's easier to track?

**Comment by manavo** [comment]
Moved to issue #6, and added some extra detail there @hi019

**Comment by jasonbosco** [comment]
Thank you @hi019 and @AbdullahFaqeir for making this happen, and thank you to everyone who helped beta test this change!
