### ISSUE TITLE
Error in tinker when trying to access `\Typesense\LaravelTypesense\Typesense` singleton

### ISSUE THREAD

**Issue by manavo** [typesense/laravel-scout-typesense-driver#10]
## Description

There's an error when trying to create/access the Typesense instance in the tinker console.

Although the library is working fine through the web app, it just fails here in the console.

## Steps to reproduce

```
$ php artisan tinker
Psy Shell v0.10.8 (PHP 8.0.2 — cli) by Justin Hileman
>>> app()->make(\Typesense\LaravelTypesense\Typesense::class);
TypeError: Typesense\LaravelTypesense\TypesenseServiceProvider::Typesense\LaravelTypesense\{closure}(): Argument #1 ($client) must be of type Typesense\Client, Illuminate\Foundation\Application given, called in /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 869
```

## Expected Behavior

I'd expect the Typesense class/singleton to be returned

## Actual Behavior

I get the error returned above.

## Metadata

**Typsense Version**: 0.21.0

**OS**: Ubuntu 18.04.5 LTS

**Comment by hi019** [comment]
Fixed by #11
