### ISSUE TITLE
 Http\Discovery\NotFoundException     No HTTPlug clients found.

### ISSUE THREAD

**Issue by edsonfeimberg** [typesense/laravel-scout-typesense-driver#14]
I am currently experimenting with algolia, meilisearch and typsense, and typsense driver was the only one to fail after trying:

php artisan scout:import "App\Brand"

 Http\Discovery\NotFoundException 

  No HTTPlug clients found. Make sure to install a package providing "php-http/client-implementation". Example: "php-http/guzzle6-adapter".

is this an expected behaviour?

**Comment by hi019** [comment]
Hey. You'll need to install an adapter for your specific `guzzlehttp/guzzle` version. Laravel 8 includes guzzle7, so do `composer require php-http/guzzle7-adapter`

**Comment by edsonfeimberg** [comment]
i tried it and now i get:

php artisan scout:import "App\Brand"

   JsonException 

  Syntax error

  at vendor/typesense/typesense-php/src/ApiCall.php:235

**Comment by hi019** [comment]
@edsonfeimberg What's your PHP version? Can you try with v5.0.1-rc3 of this package?

**Comment by edsonfeimberg** [comment]
Sorry for the late response. Only came back to experimenting with Typesense these days. Not sure is something was updated, but now everything is working perfectly. Sorry one more time for the late response and thank you for your support.

**Comment by hi019** [comment]
No problem, I'm glad it's fixed :)
