### ISSUE TITLE
Detail regarding composer installation

### ISSUE THREAD

**Issue by hilmanski** [typesense/laravel-scout-typesense-driver#21]
HI.. Try to install this package locally 

through command:
`composer require typesense/laravel-scout-typesense-driver`

Error:

```
[InvalidArgumentException]
  Package typesense/laravel-scout-typesense-driver has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version
```
  
  Any information about what and which version I should fix?

**Comment by AbdullahFaqeir** [comment]
Hello @hilmanski 

Can you please show me your composer.json file and the php version you're currently working on?

**Comment by hilmanski** [comment]
Sure @AbdullahFaqeir  thanks before.
I'm on php7.4 macOS Catalina

`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/fortify": "^1.10",
        "laravel/framework": "^8.75",
        "laravel/nova": "*",
        "laravel/sanctum": "^2.11",
        "laravel/scout": "^9.4",
        "laravel/tinker": "^2.5",
        "league/flysystem-aws-s3-v3": "~1.0",
        "numaxlab/nova-ckeditor5-classic": "^1.1",
        "optimistdigital/nova-multiselect-field": "^2.3",
        "php-http/guzzle7-adapter": "^1.0",
        "predis/predis": "^1.1",
        "rap2hpoutre/laravel-log-viewer": "^2.0",
        "spatie/laravel-backup": "^6.16",
        "whitecube/nova-flexible-content": "^0.2.8"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.6",
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^5.10",
        "phpunit/phpunit": "^9.5.10"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        },
        "files": [
            "app/helpers.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "repositories": [
        {
            "type": "path",
            "url": "./nova"
        }
    ]
}
`

**Comment by AbdullahFaqeir** [comment]
Hello @hilmanski,

As part of supporting laravel 9, we had to drop support for php versions lower than 8.x

```
"php": "^7.3|^8.0",
```

This part, you need to drop ^7.3

**Comment by hilmanski** [comment]
Thanks for your confirmation.
That's unfortunate. Possible to install specific version? support L8 below?

**Comment by AbdullahFaqeir** [comment]
Yes, you can use the version [v5.0.2](https://github.com/typesense/laravel-scout-typesense-driver/releases/tag/v5.0.2)

**Comment by hilmanski** [comment]
Not working so far. With same composer config
I move back to 5.0.0

composer require typesense/laravel-scout-typesense-driver:5.0.0

```
  [InvalidArgumentException]
  Package typesense/laravel-scout-typesense-driver at version 5.0.0 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version
```

**Comment by maykon** [comment]
I got the same problem running on PHP 7.4.14 and "php": "^7.4" on composer.

**Comment by karakhanyans** [comment]
@hilmanski @maykon Hi. 

Our Laravel Scout Typesense Driver supports PHP starting from version 8.0, unfortunately, you cannot use it with PHP 7.4.
