### ISSUE TITLE
Don't update Typesense document if the model is soft-deleted

### ISSUE THREAD

**Issue by ingria** [typesense/laravel-scout-typesense-driver#22]
## Description

Typesense driver does not check if the model is soft deleted and always updates the data when the model changes. This causes the soft-deleted document to be created in the collection. 

## Steps to reproduce

For example, in my case I have some searchable model with `SoftDeletes` trait and observer that clears some meta fields **after** the model is deleted. Something like that:

```php
class MyModelObserver
{
    public function deleted(MyModel $model)
    {
        $model->update(['worker_id' => null, 'support_id' => null]);
    }
}

// ...

MyModel::delete(id); // The model is still in Typesense
```

I presume that if I do something like `MyModel::withTrashed()->find(id)->update(['name' => 'test'])`, the model will be also pushed to the Typesense.

## Expected Behavior

The Typesense driver should not update the remote document if the model is in soft-deleted state.

## Actual Behavior

Typesense deletes the remote document and immediately restores it (because `MyModelObserver` calls the `update` method on the model.

Also note that `worker_id` and `support_id` is not even in the model schema (see #23).

## Metadata

**Typsense Version**: 5.0

**OS**: Ubuntu 20.04

**Comment by karakhanyans** [comment]
Hi @ingria 

The bug has been fixed, https://github.com/typesense/laravel-scout-typesense-driver/pull/60

Thanks for reporting this, 

Closing the PR.
