### ISSUE TITLE
Not able to skip an object from being indexed

### ISSUE THREAD

**Issue by nicomengual** [typesense/laravel-scout-typesense-driver#24]
## Description

Problems when trying to skip an object so it DOES NOT become part of the index. There's no apparent way to do it using the function `toSearchableArray`

## Steps to reproduce

The problem seems to be the function toSearchableArray

if I want to bypass an object on that function (ie: I don't want it into the index):

1- Returning an empty array results in a malformed JASON error when syncing:
```
 Typesense\Exceptions\TypesenseClientError 

  Error importing document: Bad JSON: not a properly formed document.
  
  at vendor/typesense/laravel-scout-typesense-driver/src/Typesense.php:165
```

2- Returning FALSE results in an error of unexpected response type:
```
  TypeError 

  Typesense\Documents::Typesense\{closure}(): Argument #1 ($document) must be of type array, bool given

  at vendor/typesense/typesense-php/src/Documents.php:139
```

3- if I use the Scout method 'unsearchable()' function results in an ObjectNotFound exception:
```
 Typesense\Exceptions\ObjectNotFound 

  Could not find a document with id: 1105

  at vendor/typesense/typesense-php/src/ApiCall.php:347

```

## Expected Behavior

Ideally, if we would like this to work like Algolia does with Laravel Scout, by using the `unsearchable` method and returning either an empty array or a false flag, we would be able to skip the object from being added to the index.

## Actual Behavior

The import is interrupted with one of those exceptions and the collection is being indexed only up to the point of the first failure.

## Metadata

**Typsense Version**: 0.2.22

**OS**: Ubuntu 22.04

**Comment by MeisamMulla** [comment]
I was having this issue as well and found this in the documentation that helped

https://laravel.com/docs/9.x/scout#conditionally-searchable-model-instances

**Comment by BrandonJamesBorders** [comment]
If you guys want to use this, you can update your composer.json 

In require:
`"typesense/laravel-scout-typesense-driver": "dev-patch-1"`

Add or update your repositories:
```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/BrandonJamesBorders/laravel-scout-typesense-driver"
    }
]
```

Then run `composer update`

**Comment by karakhanyans** [comment]
Hi @nicomengual 

This solution should work for you: https://laravel.com/docs/9.x/scout#conditionally-searchable-model-instances

Just add following inside your model and return false whenever you don't want to sync that model.

```
/**
 * Determine if the model should be searchable.
 *
 * @return bool
 */
public function shouldBeSearchable()
{
    return $this->isPublished();
}
```

Let me know if this solves your problem.

Thanks.

**Comment by karakhanyans** [comment]
Closing this issue due to provided solution.
