### ISSUE TITLE
Question : Use filter_by or complex query

### ISSUE THREAD

**Issue by cephee** [typesense/laravel-scout-typesense-driver#26]
## Description
Hello everyone,

I would like to know if it is possible (if so, how?) to be able to use the `filter_by` in order to be able to add filter conditions such as
`'price:<=25'` ? As given as an example here in the Typesense documentation :
https://typesense.org/docs/0.22.2/api/documents.html#search and 
https://typesense.org/docs/0.22.2/api/documents.html#search-parameters

Since it is not possible in Laravel Scout to use complex Where clause 

> Scout allows you to add simple "where" clauses to your search queries. Currently, these clauses only support basic numeric equality checks and are primarily useful for scoping search queries by an owner ID. Since a search index is not a relational database, more advanced "where" clauses are not currently supported

Thank you in advance for your answer

**Comment by felipehertzer** [comment]
Hi @cephee, currently there is no way to change the logical operator by parameters. an alternative is to concatenate the logical operator with the value as in the code below. This will likely be fixed.

```php
$builder->where("date", ["<=" . $date]);
```

**Comment by cephee** [comment]
Thank you for the answer :). I will try to use this.

I updated my pull request #27 related to another issue #19 so that we can continue to use the where clause the same way. (Thanks again for the feedback, this allowed me to make this change)
