### ISSUE TITLE
Grouping isn't supported by the map result function

### ISSUE THREAD

**Issue by denizaygun** [typesense/laravel-scout-typesense-driver#31]
## Description

When utilising the `groupBy` macro, the `map` functin from the `TypesenseEngine.php` fails as the Typesense API returns `grouped_hits` and not a `hits` index.

My workaround was to implement a custom macro: 
```
Builder::macro('getGroup', function () {
            $results = $this->engine()->search($this);

            $objectIds = collect($results['grouped_hits'] ?? $results['hits'])
                ->pluck(isset($results['grouped_hits']) ? 'group_key.0' : 'document.id')
                ->values()
                ->all();

            if (isset($results['grouped_hits'])) {
                return collect(array_values($objectIds));
            }

            return null;
        });
```
I then call this conditionally based on if I need a grouping to be applide with:
```
if ($groupBy) {
      return $query->getGroup();
}
```

This can be integrated to the `map` function quite easily but perhaps a seperate `mapByGroup` may be better. 

## Steps to reproduce

Perform a search with the `->groupBy()` macro.

## Expected Behavior
The TypesenseEngine should be able to map the grouped_hits index.

## Actual Behavior
The TypesenseEngine fails to map the grouped_hits as it expects a `hits` index and therefore fails.

## Metadata

**Typsense Version**: v5.1.0

**OS**: MacOS 12.4 Monterey

**Comment by karakhanyans** [comment]
Hi @denizaygun, thanks for finding this bug. 

It has been fixed in this PR: https://github.com/typesense/laravel-scout-typesense-driver/pull/41

Thanks.
