### ISSUE TITLE
Document not updated if 'afterCommit' is true

### ISSUE THREAD

**Issue by bin-emanuele** [typesense/laravel-scout-typesense-driver#44]
## Description

The TypesenseEngine::update will check if the model is dirty, but if the 'afterCommit' is set to true in the config, the method will always skip.

## Steps to reproduce

- set scout.after_commit to true
- trigger a save event on a Searchable model

## Expected Behavior

TypesenseEngine::update should update the model, ignoring the 'isDirty' if 'afterCommit' is set to true.

## Actual Behavior

TypesenseEngine::update skips the update.

## Metadata

**Typesense Version**: 0.24.0

typesense/laravel-scout-typesense-driver: v5.2.0,
laravel/scout: v9.8.0

**OS**: Ubuntu 22.04

**Comment by manavo** [comment]
This is also referencing `isDirty` the same as #45, and v5.2.0 which was rolled back.

Are they both about the same issue?
