### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by shoaibsharif** [typesense/laravel-scout-typesense-driver#48]
## Description

Currently the package doesn't support Laravel 10

## Steps to reproduce

Install typesense driver package in laravel 10 and I can't run composer update

## Expected Behavior

Should be able to work in Laravel 10

## Metadata

**Typesense Version**: 4

**OS**: MacOS

**Comment by manavo** [comment]
#52 fixes this, just waiting for it to get approved and hopefully merged

@AbdullahFaqeir? @jasonbosco?

**Comment by karakhanyans** [comment]
#52 approved and merged. Thank you @manavo and @shoaibsharif !!

**Comment by manavo** [comment]
Thanks @karakhanyans! If we could just have a quick tag/release as well, that'd be great! 🙂

**Comment by manavo** [comment]
@karakhanyans any thoughts on getting a release out with Laravel 10 support?

**Comment by karakhanyans** [comment]
Hey @manavo 
Let me prepare the release 👌

**Comment by manavo** [comment]
Thanks @karakhanyans! I just tried to upgrade, but now I get a conflict on `symfony/http-client`, which seems to have been added here as a new dependency: https://github.com/typesense/laravel-scout-typesense-driver/commit/0748b8145f67c1359de92515eb8f460645715d89

Based on the commit message, I'm guessing it should be added to `require-dev`? If needed at all?

**Comment by karakhanyans** [comment]
@manavo mmm, is it because you had one there or why it's conflicting on your side?

**Comment by karakhanyans** [comment]
@manavo I moved the symfony/http-client to require dev

https://github.com/typesense/laravel-scout-typesense-driver/pull/55

**Comment by manavo** [comment]
Thanks!
