### ISSUE TITLE
Error from Typesense on Update of Model Instance which is not in index

### ISSUE THREAD

**Issue by dervinz** [typesense/laravel-scout-typesense-driver#58]
- typesense/laravel-scout-typesense-driver: 5.2.2
- Scout Version: 9.8.1
- Scout Driver: Typesense  
- Laravel Version: 9.52.4
- PHP Version: 8.1
- Database Driver & Version:  10.2.44-MariaDB

### Description:

If an instance of a model is created & persisted in DB and should not be searchable yet (e.g. the instance is not public yet) - everything works fine.

When the same instace is beeing saved again, an error occurs and the model cannot be saved.
I guess that the reason is, that on /vendor/laravel/scout/src/ModelObserver.php:102 the Method  `$model->wasSearchableBeforeUpdate()` returns true, even though the instance of the model is not in the index yet.
The problem occurs for all Models in Index, as soon as the `shouldBeSearchable()` Method returns false (eg if the instance is not public yet).

ModelObserver.php:101ff

`...
if (! $model->shouldBeSearchable()) {
            if ($model->wasSearchableBeforeUpdate()) {
                $model->unsearchable();
            }
            return;
        }
...`

<img width="803" alt="scout1" src="https://user-images.githubusercontent.com/658573/227294370-d32e0a92-61b8-4078-ab5e-d6906490115c.PNG">

**Comment by karakhanyans** [comment]
Hi @dervinz 

Thanks for reporting this, I will take a look.

**Comment by karakhanyans** [comment]
Hi @dervinz 

The issue has been fixed here: https://github.com/typesense/laravel-scout-typesense-driver/pull/59
