### ISSUE TITLE
PHP 8.2 deprecation warnings

### ISSUE THREAD

**Issue by laacz** [typesense/laravel-scout-typesense-driver#62]
## Description

PHP 8.2 throws deprecation warning on using ${var} in strings.

## Steps to reproduce

Just use PHP 8.2

## Expected Behavior

No error shown.

## Actual Behavior

```
PHP message: PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /var/www/starfish/vendor/typesense/laravel-scout-typesense-driver/src/Typesense.php on line 195
```

## Metadata

**Typesense Version**: any
**OS**: linux

**Comment by arayiksmbatyan** [comment]
Hi @laacz,
Deprecation warning is fixed.
