### ISSUE TITLE
"Undefined property: Laravel\\Scout\\Builder::$whereIns",

### ISSUE THREAD

**Issue by CaReS0107** [typesense/laravel-scout-typesense-driver#69]
## Description

After uploading the file to Typesense, try to search over it using 
MediaSource::search($request->input('search'))
            ->paginateRaw()
            ->getCollection()
           
Got error
  "message": "Undefined property: Laravel\\Scout\\Builder::$whereIns",
 vendor/typesense/laravel-scout-typesense-driver/src/Engines/TypesenseEngine.php"
"line": 396,

**Comment by kumarkishan070997** [comment]
Hi. I am also getting the same issue. This issue is close but can anyone suggest how will it be fixed ?
