### ISSUE TITLE
   $model->unsearchable(); does not work

### ISSUE THREAD

**Issue by CaReS0107** [typesense/laravel-scout-typesense-driver#71]
## Description

When I upload new document document content is extracted and indexed on typesense which is very good.
The issue is when I delete the document I'm falling into the observer delete event, doing :
   $model->unsearchable(); and it seems it not unsearchable it from typesense

## Steps to reproduce

Upload the document it will be indexed
Delete the document and try to search by some text which was in that text, you will see that that result would be the deleted document

## Expected Behavior

When the document is deleted in goes to    $model->unsearchable(), and it should be unindexed from typesense maybe delete from there. And when I search I should gen no results since the document was deleted

**Comment by karakhanyans** [comment]
Hi @CaReS0107 

Thanks for reporting this issue, we will prioritise it and solve.

**Comment by karakhanyans** [comment]
Hi @CaReS0107 

When you use $model->delete(...) the model events are not triggering, that's why unsearchable is not working.
To avoid this, you should select the model first, like $model = Model::find($id); and then $model->delete(); in that case, events are getting fired and all works. 

Let me know if you have any further questions.

**Comment by CaReS0107** [comment]
Hey, @karakhanyans from my tests I was trying to `find ()->delete()`, also `$model->delete()`,` $model->forceDelete()`, for all these cases I fell in the delete event.
In the end, I install `typesense/typesense-php` package and in my observer delete method. I call their method for deleting

$client->collections[(new MediaSource())->searchableAs()]
    ->documents[$this->mediaSourceId]
    ->delete();       
                
and all good now. But definitely will be best to use `$model-> unsearchable()`

**Comment by karakhanyans** [comment]
@CaReS0107 as I understood, you are using typesense-php package in the laravel project, instead of using scout-typesense-driver, am I right?

**Comment by CaReS0107** [comment]
@karakhanyans  I use them both,  from typesense/typesense-php I used only the delete method

**Comment by karakhanyans** [comment]
@CaReS0107 is there any other way we can assist you here in this topic?

**Comment by karakhanyans** [comment]
The issue has been solved. Closing the PR.
