### ISSUE TITLE
Cannot index collection with a soft deleted first model when scout.soft_delete is true

### ISSUE THREAD

**Issue by vivdesign** [typesense/laravel-scout-typesense-driver#77]
## Description

When indexing with scout.soft_delete set to true index is not imported if the first model of the Collection is deleted

## Steps to reproduce

use scout:import command to import a collection of models where the first one is deleted, when scout.soft_delete is true

## Expected Behavior

The collection should be indexed

## Actual Behavior

The collection is not indexed

## Metadata

**Typesense Version**: 0.23.1

**OS**: Linux

We propose the following modification on line 171 of src/Engines/TypesenseEngine (the update method)
From this:
`if (!$this->usesSoftDelete($models->first()) || is_null($models->first()?->deleted_at)) {`
To this:
`if (!$this->usesSoftDelete($models->first()) || is_null($models->first()?->deleted_at) || config('scout.soft_delete', false)) {`

**Comment by turbo124** [comment]
Just hit this myself +1 for the fix here.

**Comment by karakhanyans** [comment]
The issue has been solved. Closing the PR.
