### ISSUE TITLE
Hotfix TypeError - Typesense\\Documents::import(): Argument #1 ($documents) must be of type string, array given. 

### ISSUE THREAD

**Issue by ARTWINPRO** [typesense/laravel-scout-typesense-driver#81]
## Description
Afrer migrate from (v5.2.8 => v5.2.6) got the type error. 
`
"Typesense\\Documents::import(): Argument #1 ($documents) must be of type string, array given, called in /var/www/artwin.io/vendor/typesense/laravel-scout-typesense-driver/src/Typesense.php on line 191"
exception: "TypeError"
file: "./vendor/typesense/typesense-php/src/Documents.php"
`

## Metadata

**Typesense Version**: v5.2.8

--- 

Before and after method changes fallow up on the screenshots. 
---
 v5 2 6

<img width="1041" alt="v5 2 6" src="https://github.com/typesense/laravel-scout-typesense-driver/assets/16427316/3d0c5d1b-2030-4778-ae9b-b74e074c6ec7">
---
v5 2 8
<img width="805" alt="v5 2 8" src="https://github.com/typesense/laravel-scout-typesense-driver/assets/16427316/dc83be45-f8ec-44d5-a18d-defa2ebd78c5">

**Comment by ARTWINPRO** [comment]
Trace log:
`
[2023-11-29 14:51:55] local.ERROR: Typesense\Documents::import(): Argument #1 ($documents) must be of type string, array given, called in /var/www/domain/vendor/typesense/laravel-scout-typesense-driver/src/Typesense.php on line 190 {"userId":2,"exception":"[object] (TypeError(code: 0): Typesense\\Documents::import(): Argument #1 ($documents) must be of type string, array given, called in /var/www/domain/vendor/typesense/laravel-scout-typesense-driver/src/Typesense.php on line 190 at /var/www/domain/vendor/typesense/typesense-php/src/Documents.php:97)
[stacktrace]
#0 /var/www/domain/vendor/typesense/laravel-scout-typesense-driver/src/Typesense.php(190): Typesense\\Documents->import(Array, Array)
#1 /var/www/domain/vendor/typesense/laravel-scout-typesense-driver/src/Engines/TypesenseEngine.php(172): Typesense\\LaravelTypesense\\Typesense->importDocuments(Object(Typesense\\Collection), Array)
#2 /var/www/domain/vendor/laravel/scout/src/Searchable.php(63): Typesense\\LaravelTypesense\\Engines\\TypesenseEngine->update(Object(Illuminate\\Database\\Eloquent\\Collection))
#3 /var/www/domain/vendor/laravel/scout/src/Searchable.php(42): App\\Models\\BaseModel->queueMakeSearchable(Object(Illuminate\\Database\\Eloquent\\Collection))
#4 /var/www/domain/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php(123): Illuminate\\Database\\Eloquent\\Collection->Laravel\\Scout\\{closure}()
#5 /var/www/domain/vendor/laravel/scout/src/Searchable.php(183): Illuminate\\Support\\Collection->__call('searchable', Array)
#6 /var/www/domain/vendor/laravel/scout/src/ModelObserver.php(109): App\\Models\\BaseModel->searchable()
#7 /var/www/domain/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(478): Laravel\\Scout\\ModelObserver->saved(Object(App\\ApiModels\\ApiUser))
#8 /var/www/domain/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('eloquent.saved:...', Array)
#9 /var/www/domain/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners('eloquent.saved:...', Array, false)
#10 /var/www/domain/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(188): Illuminate\\Events\\Dispatcher->dispatch('eloquent.saved:...', Array)
#11 /var/www/domain/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1176): Illuminate\\Database\\Eloquent\\Model->fireModelEvent('saved', false)
#12 /var/www/domain/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1149): Illuminate\\Database\\Eloquent\\Model->finishSave(Array)
#13 /var/www/domain/app/ApiModels/ApiUser.php(618): Illuminate\\Database\\Eloquent\\Model->save()
`

**Comment by ARTWINPRO** [comment]
Laravel scout: v10.6.0

**Comment by Muffinman** [comment]
I believe this is the same bug I had here:

https://github.com/typesense/laravel-scout-typesense-driver/issues/75

I just stumbled across this myself, for some reason composer is STILL by default installing an old version. No idea why!

Solution (for me):

`composer require -W typesense/laravel-scout-typesense-driver:^5.2.7`

**Comment by ARTWINPRO** [comment]
> I believe this is the same bug I had here: #75
> 
> I just stumbled across this myself, for some reason composer is STILL by default installing an old version. No idea why!
> 
> Solution (for me):
> 
> `composer require -W typesense/laravel-scout-typesense-driver:^5.2.7`

I had already installed 5.2.8. The trouble is with Laravel Scout. This package is still don't support scout v10.6.0

**Comment by karakhanyans** [comment]
The issue has been fixed with the latest release. Closing this issue.
